services:
  ipfs_node:
    container_name: ipfs_node
    image: ipfs/kubo:v0.34.1
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8080:8080" # ipfs gateway
    volumes:
      - ./data/ipfs_data:/data/ipfs
    networks:
      - trusted_peer_net

  ipfs_cluster:
    container_name: ipfs_cluster
    image: ipfs/ipfs-cluster@sha256:5df90b8d848a74a8505feb3684bf6d74ec6ab869e6f3de692b842f07c1a5ed1a
    depends_on:
      - ipfs_node
    environment:
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs_node/tcp/5001
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # expose API
    ports:
      - "9094:9094" # http api
      - "9095:9095" # proxy api
      - "9096:9096" # cluster swarm, other peers connect via this port
    volumes:
      - ./data/ipfs_cluster_data:/data/ipfs-cluster
      - target:/usr/local/share/target
    networks:
      - trusted_peer_net

  watcher:
    container_name: watcher
    build:
      context: .
      dockerfile: ./watcher/Dockerfile
    depends_on:
      - ipfs_node
      - ipfs_cluster
    volumes:
      - target:/usr/share/target
      - ./data/ipns_data:/usr/share/ipns_data
      - ./metrics:/usr/share/metrics
    networks:
      - trusted_peer_net

networks:
  trusted_peer_net:

volumes:
  ipfs_data:
  ipfs_cluster_data:
  target:
