#!/bin/sh
set -e

user=ipfs
repo="/ipfs_data"

if [ "$(id -u)" -eq 0 ]; then
  echo "Changing user to $user"
  # ensure folder is writable
  gosu "$user" test -w "$repo" || chown -R -- "$user" "$repo"
  # restart script with new privileges
  exec gosu "$user" "$0" "$@"
fi

# 2nd invocation with regular user
ipfs version


if [ -e "$repo" ]; then
  echo "Found IPFS fs-repo at $repo"
else
  echo "Creating IPFS fs-repo at $repo"
  ipfs daemon --init --init-config=config --enable-namesys-pubsub
  ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
  ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
fi

exec ipfs "$@"